name: find_weather_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.7
  google_fonts: ^4.0.3
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  dio: ^4.0.6
  flutter_svg: ^1.1.6
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/images/
    - assets/icons/
